### ISSUE TITLE
LZMA issue on resources

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#10]
maybe same as in prev issues, but not sure...

logs

```
...
←[0;32;40m928   [1] INFO  UnConfuserEx    - Successfully removed ControlFlow protection←[0m
←[0;32;40m933   [1] INFO  UnConfuserEx    - Resources detected, attempting to remove←[0m
←[0;31;40;1;4m946   [1] FATAL UnConfuserEx    - Caught exception when trying to remove Resources protection←[0m
←[0;31;40;1m959   [1] ERROR UnConfuserEx    - SevenZip.DataErrorException: Data Error
   at SevenZip.Compression.LZMA.Decoder.Code(Stream inStream, Stream outStream, Int64 inSize, Int64 outSize, ICodeProgress progress)
   at UnConfuserEx.Utils.DecompressDataLZMA(Byte[] data) in c:\Tmp\unc-2\UnConfuserEx\Utils.cs:line 44
   at UnConfuserEx.Protections.ResourcesRemover.DecompressData() in c:\Tmp\unc-2\UnConfuserEx\Protections\Resources\ResourcesRemover.cs:line 228
   at UnConfuserEx.Protections.ResourcesRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc-2\UnConfuserEx\Protections\Resources\ResourcesRemover.cs:line 101
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc-2\UnConfuserEx\UnConfuserEx.cs:line 64←[0m
```

[target ](https://www.sendspace.com/file/b3s3st)

**Comment by MadMin3r** [comment]
Yeah this is the same as #8, will close this one
