### ISSUE TITLE
SwitchDeobfuscator issues

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#2]
Tried to deobf some confused assemblies recently and hit these kind of issues:

```
←[0;36;40;2m7501  [1] DEBUG ControlFlow     - Removing obfuscation from method System.Object ?????????????????????????????????????????::?????????????????????????????????????????(System.String&,System.
Int32&,System.Int16&)←[0m
←[0;31;40;1m7506  [1] ERROR ControlFlow     - Failed to remove obfuscation for method System.Object ?????????????????????????????????????????::?????????????????????????????????????????(System.String&,
System.Int32&,System.Int16&) (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))←[0m
←[0;31;40;1m7511  [1] ERROR ControlFlow     -    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.DeobfuscateSwitchBlock() in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 162
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.Deobfuscate(Block block) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 40
   at de4dot.blocks.cflow.BlockDeobfuscator.Deobfuscate(List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate(IEnumerable`1 bds, List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate()
   at UnConfuserEx.Protections.ControlFlowRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\ControlFlowRemover.cs:line 61←[0m
←[0;36;40;2m7528  [1] DEBUG ControlFlow     - Removing obfuscation from method System.Void $"Wy'1d'qAlV0y*d+_\qx":r"::?????????????????????????????????????????(System.ComponentModel.BackgroundWorker,S
ystem.ComponentModel.DoWorkEventArgs)←[0m
←[0;31;40;1m7535  [1] ERROR ControlFlow     - Failed to remove obfuscation for method System.Void $"Wy'1d'qAlV0y*d+_\qx":r"::?????????????????????????????????????????(System.ComponentModel.BackgroundW
orker,System.ComponentModel.DoWorkEventArgs) (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))←[0m
←[0;31;40;1m7539  [1] ERROR ControlFlow     -    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.DeobfuscateSwitchBlock() in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 162
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.Deobfuscate(Block block) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 40
   at de4dot.blocks.cflow.BlockDeobfuscator.Deobfuscate(List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate(IEnumerable`1 bds, List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate()
   at UnConfuserEx.Protections.ControlFlowRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\ControlFlowRemover.cs:line 61←[0m
←[0;31;40;1m7555  [1] ERROR ControlFlow     - Removed obfuscation from 0 methods. Failed to remove from 7 methods←[0m
```

**Comment by greenozon** [comment]
https://github.com/MadMin3r/UnconfuserEx/blob/da95fd4737be2be71012f09671de1365ec1c1645/UnConfuserEx/Protections/ControlFlow/SwitchDeobfuscator.cs#L162C53-L162C61

nextCase var is having negative index  ...

**Comment by MadMin3r** [comment]
Would you mind uploading the binary you're trying to deobfuscate somewhere? If you can, I'll take a look at this.

**Comment by greenozon** [comment]
hi @MadMin3r 
thanks for lightning fast reply!

here it [is](https://www.sendspace.com/file/d4u4cy)

PS it hit another issues, I'll open another issues in order to not overload this one...

**Comment by greenozon** [comment]
Just in case the original sources were referencing .NET 7.0 (but it already obsoleted and [died](https://endoflife.date/dotnet))
so I"ve built using .NET8

and here is my runtime config json

```
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "8.0.0"
      }
    ],
    "configProperties": {
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": true
    }
  }
}
```

**Comment by MadMin3r** [comment]
Could you give the changes in this branch a go: [fix-switch-deobfuscator](https://github.com/MadMin3r/UnconfuserEx/tree/fix-switch-deobfuscator). Should fix this and #3

**Comment by greenozon** [comment]
Exciting news! will give it a try shortly!

**Comment by greenozon** [comment]
@MadMin3r   test succeed,
very well done, kudos!

BTW, I've never seen this syntax in C# before:

```
                    switchLocal = instrs[^4].Instruction.GetLocal(locals);
```
^4  I mean
is it kind of some fancy stuff from modern C# version?

PS feel free to close the ticket

**Comment by MadMin3r** [comment]
Yeah it's just a way to index from the end of an array instead of the start. Looks neater than getting the length and subtracting from that.
