### ISSUE TITLE
add support for input files without absolute path

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#4]
Would it be OK to add also support for files from current dir? (most used case in my case)
it looks like currently the tool requires Absolute Paths only...

example:

```
c:\Tmp\unc\UnConfuserEx\bin\Debug\net8.0-windows>UnConfuserEx.exe test2.dll
←[0;32;40m203   [1] INFO  UnConfuserEx    - Renamer detected, attempting to remove←[0m
←[0;32;40m270   [1] INFO  UnConfuserEx    - Successfully removed Renamer protection←[0m
←[0;32;40m273   [1] INFO  UnConfuserEx    - All detected protections removed. Writing new module to \test2-deobfuscated.dll←[0m
←[0;31;40;1m280   [1] ERROR UnConfuserEx    - Failed to write module←[0m
←[0;31;40;1m296   [1] ERROR UnConfuserEx    - System.UnauthorizedAccessException: Access to the path 'c:\test2-deobfuscated.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc\UnConfuserEx\UnConfuserEx.cs:line 98←[0m
```

**Comment by MadMin3r** [comment]
Done, let me know if you still have any issues.

**Comment by greenozon** [comment]
works perfectly!
I wish all fixes would be a single liners :)
thanks
