### ISSUE TITLE
Issue writing output result: dnlib.DotNet.Writer.ModuleWriterException: Error calculating max stack value.

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#5]
example:

```
c:\Tmp\unc\UnConfuserEx\bin\Debug\net8.0-windows>UnConfuserEx.exe c:\Tmp\unc\UnConfuserEx\bin\Debug\net8.0-windows\test2.dll
←[0;32;40m198   [1] INFO  UnConfuserEx    - Renamer detected, attempting to remove←[0m
←[0;32;40m268   [1] INFO  UnConfuserEx    - Successfully removed Renamer protection←[0m
←[0;32;40m270   [1] INFO  UnConfuserEx    - All detected protections removed. Writing new module to c:\Tmp\unc\UnConfuserEx\bin\Debug\net8.0-windows\test2-deobfuscated.dll←[0m
←[0;31;40;1m561   [1] ERROR UnConfuserEx    - Failed to write module←[0m
←[0;31;40;1m575   [1] ERROR UnConfuserEx    - dnlib.DotNet.Writer.ModuleWriterException: Error calculating max stack value. If the method's obfuscated, set CilBody.KeepOldMaxStack or MetadataOptions.F
lags (KeepOldMaxStack, global option) to ignore this error. Otherwise fix your generated CIL code so it conforms to the ECMA standard. Error occurred after metadata event BeginWriteMethodBodies during
 writing method 'System.Reflection.MethodInfo Class0::StaticMethod5(System.Type,System.String,System.Type[])' (0x06000008).
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.Metadata.Error(String message, Object[] args)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.IWriterError.Error(String message)
   at dnlib.DotNet.Writer.MethodBodyWriter.ErrorImpl(String message)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.Error(String message)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.GetMaxStack()
   at dnlib.DotNet.Writer.MethodBodyWriter.Write()
   at dnlib.DotNet.Writer.Metadata.WriteMethodBodies()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc\UnConfuserEx\UnConfuserEx.cs:line 98←[0m
```

input is over [here](https://www.sendspace.com/file/oeha4l)

**Comment by MadMin3r** [comment]
~~Are you sure this is protected with ConfuserEx? All methods are encrypted which is why writing fails, but it doesn't look like the anti tamper from ConfuserEx (Unless they've added a new version of that)?~~

This is using the JIT anti tamper which I haven't added support for.

**Comment by greenozon** [comment]
Thank you for update!

**Comment by MadMin3r** [comment]
Had another look at this one and I'm back to thinking it isn't a valid binary? Not sure why I thought it was using JIT anti tamper 🤔 

I can see the correct decryption function in the default module, but it's never called by the module cctor and the encrypted section is missing from the PE header?

**Comment by greenozon** [comment]
yeah, smth is unclear, lets leave it alone :)
