### ISSUE TITLE
Fatal error during Constants removal phase

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#6]
example (in end of logs)
thus no any artifact produced

```
[0;32;40m20771 [1] INFO  UnConfuserEx    - Constants detected, attempting to remove[0m
[0;31;40;1;4m20780 [1] FATAL UnConfuserEx    - Caught exception when trying to remove Constants protection[0m
[0;31;40;1m20780 [1] ERROR UnConfuserEx    - System.OverflowException: Arithmetic operation resulted in an overflow.
   at SevenZip.Compression.LZ.OutWindow.Create(UInt32 windowSize)
   at SevenZip.Compression.LZMA.Decoder.SetDictionarySize(UInt32 dictionarySize)
   at SevenZip.Compression.LZMA.Decoder.SetDecoderProperties(Byte[] properties)
   at UnConfuserEx.Utils.DecompressDataLZMA(Byte[] data) in c:\Tmp\unc\UnConfuserEx\Utils.cs:line 29
   at UnConfuserEx.Protections.ConstantsRemover.DecompressData() in c:\Tmp\unc\UnConfuserEx\Protections\Constants\ConstantsRemover.cs:line 324
   at UnConfuserEx.Protections.ConstantsRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc\UnConfuserEx\Protections\Constants\ConstantsRemover.cs:line 97
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc\UnConfuserEx\UnConfuserEx.cs:line 64[0m
```

[input](https://www.sendspace.com/file/ell2oo)

**Comment by MadMin3r** [comment]
Fixed
