### ISSUE TITLE
Issues at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.IsSwitchBlock

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#7]
sample logs

```
...
[0;31;40;1m15639 [1] ERROR ControlFlow     -    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.IsSwitchBlock(Block curBlock) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 59
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.Deobfuscate(Block block) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 38
   at de4dot.blocks.cflow.BlockDeobfuscator.Deobfuscate(List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate(IEnumerable`1 bds, List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate()
   at UnConfuserEx.Protections.ControlFlowRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\ControlFlowRemover.cs:line 61[0m
[0;36;40;2m15639 [1] DEBUG ControlFlow     - Removing obfuscation from method System.Void ClassLibrary1.Chung_DceSetup::?????????????????????????????????????????(System.String)[0m
[0;31;40;1m15640 [1] ERROR ControlFlow     - Failed to remove obfuscation for method System.Void ClassLibrary1.Chung_DceSetup::?????????????????????????????????????????(System.String) (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))[0m
[0;31;40;1m15640 [1] ERROR ControlFlow     -    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.IsSwitchBlock(Block curBlock) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 59
   at UnConfuserEx.Protections.ControlFlow.SwitchDeobfuscator.Deobfuscate(Block block) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\SwitchDeobfuscator.cs:line 38
   at de4dot.blocks.cflow.BlockDeobfuscator.Deobfuscate(List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate(IEnumerable`1 bds, List`1 allBlocks)
   at de4dot.blocks.cflow.BlocksCflowDeobfuscator.Deobfuscate()
   at UnConfuserEx.Protections.ControlFlowRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc\UnConfuserEx\Protections\ControlFlow\ControlFlowRemover.cs:line 61[0m
...
```

target: in #6

**Comment by MadMin3r** [comment]
Done
