### ISSUE TITLE
LZMA decompress issue

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#8]
seems similar to previous issue #6 , but not sure...

```
...
←[0;32;40m1987  [1] INFO  UnConfuserEx    - Successfully removed ControlFlow protection←[0m
←[0;32;40m1992  [1] INFO  UnConfuserEx    - Resources detected, attempting to remove←[0m
←[0;31;40;1;4m2006  [1] FATAL UnConfuserEx    - Caught exception when trying to remove Resources protection←[0m
←[0;31;40;1m2019  [1] ERROR UnConfuserEx    - SevenZip.DataErrorException: Data Error
   at SevenZip.Compression.LZMA.Decoder.Code(Stream inStream, Stream outStream, Int64 inSize, Int64 outSize, ICodeProgress progress)
   at UnConfuserEx.Utils.DecompressDataLZMA(Byte[] data) in c:\Tmp\unc-2\UnConfuserEx\Utils.cs:line 44
   at UnConfuserEx.Protections.ResourcesRemover.DecompressData() in c:\Tmp\unc-2\UnConfuserEx\Protections\Resources\ResourcesRemover.cs:line 228
   at UnConfuserEx.Protections.ResourcesRemover.Remove(ModuleDefMD& module) in c:\Tmp\unc-2\UnConfuserEx\Protections\Resources\ResourcesRemover.cs:line 101
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc-2\UnConfuserEx\UnConfuserEx.cs:line 64←[0m
```

[target ](https://www.sendspace.com/file/syj1px)

**Comment by MadMin3r** [comment]
Think I've figured out what's going wrong here but at the same time also spotted an issue where the ordering of Constants and Resources protection can cause one to be skipped... Will try and get this fixed tomorrow. ( Won't be a single line ): )

**Comment by MadMin3r** [comment]
Fixed
