### ISSUE TITLE
Failed to write module: Error calculating max stack value.

### ISSUE THREAD

**Issue by greenozon** [MadMin3r/UnconfuserEx#9]
seems similar but not sure

```
...
←[0;32;40m309   [1] INFO  UnConfuserEx    - All detected protections removed. Writing new module to c:\Tmp\unc-2\UnConfuserEx\bin\Debug\net8.0-windows7.0\test5-deobfuscated.dll←[0m
←[0;31;40;1m576   [1] ERROR UnConfuserEx    - Failed to write module←[0m
←[0;31;40;1m589   [1] ERROR UnConfuserEx    - dnlib.DotNet.Writer.ModuleWriterException: Error calculating max stack value. If the method's obfuscated, set CilBody.KeepOldMaxStack or MetadataOptions.F
lags (KeepOldMaxStack, global option) to ignore this error. Otherwise fix your generated CIL code so it conforms to the ECMA standard. Error occurred after metadata event BeginWriteMethodBodies during
 writing method 'T Class2`1::get_Zoom()' (0x06000022).
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.Metadata.Error(String message, Object[] args)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.IWriterError.Error(String message)
   at dnlib.DotNet.Writer.MethodBodyWriter.ErrorImpl(String message)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.Error(String message)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.GetMaxStack()
   at dnlib.DotNet.Writer.MethodBodyWriter.Write()
   at dnlib.DotNet.Writer.Metadata.WriteMethodBodies()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
   at UnConfuserEx.UnConfuserEx.Main(String[] args) in c:\Tmp\unc-2\UnConfuserEx\UnConfuserEx.cs:line 98←[0m
```

[target](https://www.sendspace.com/file/j471ry)

**Comment by MadMin3r** [comment]
This one is actually fixed now
